server:
  port: 9001
  servlet:
    context-path: /
spring:
  application:
    name: document-service
  datasource:
    username: thw
    password: thw19971017thw
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
#  redis:
#    host: 192.168.160.130
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 1000
#        max-idle: 100
#        min-idle: 10
#        max-wait: 10000
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
DOCUMENT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/